# Celebal Assignment 1
**Assignment: Data Engineering 003 — Week 1**  
**Dataset: Myntra Shopping Products**

## Step 1 - Loading Dataset

In [8]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:\\Users\\Asus\\Desktop\\jupter_projectes\\practice_project1\\project_submission\\archive\\Combined_dataset.csv")
print(df.shape)

(1000, 24)

## Checking the dataset

In [9]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [10]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [11]:
df.shape

(1000, 24)

In [12]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

## Handling Missing Values

In [14]:

df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [15]:
df['discount'] = df['discount'].fillna(0)

In [16]:
text_fill_cols = [
    'what_customers_said',
    'seller_name',
    'videos',
    'variations',
    'seller_information'
]

for col in text_fill_cols:
    df[col] = df[col].fillna("Not Available")

In [17]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

---
## Filtering and Selecting Data

In [18]:
premium_items = df[df['initial_price'] > 5000]

premium_items.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
17,18346134,Arrabi,Pink & Grey Striped 300 TC King Cotton Bedshee...,4.3,12,6329,76.0,"""₹6,329.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",Not Available,Not Available,"[{""size"":""Super King""}]",Not Available,Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
21,1728397,Mactree,Men Brown Solid Mid-Top Flat Boots,3.9,1727,9060,88.0,"""₹1,087.00""",INR,http://assets.myntassets.com/assets/images/172...,...,"{""1_star"":228,""2_stars"":89,""3_stars"":186,""4_st...",Not Available,MAX███ IN███NAT██████,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...",Not Available,"21/███10 ███NS █████████4 ,███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",boots
22,21427828,London Rag,Women Stiletto Heeled High-Top Boots,5.0,4,9599,60.0,"""₹3,839.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,VOL███FAS███N P█████████,"[{""size"":""3"",""value"":""23.0cm"",""value_name"":""To...",Not Available,SAI███USE███OT █████████ NA███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",boots
58,20129438,Skechers,Men Blue Textured Sneakers,3.8,11,12999,30.0,"""₹7,799.00""",INR,http://assets.myntassets.com/assets/images/201...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",LSD███FES███ES █████████IMI██████,"[{""size"":""6"",""value"":""25.0cm"",""value_name"":""To...",Not Available,118███GH ███H C█████████OGE███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
63,21321784,San Frissco,Men Colourblocked Sneakers,4.3,6,5995,72.0,"""₹1,678.00""",INR,http://assets.myntassets.com/assets/images/213...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",ARY███ FO███EAR█████████PVT██████,"[{""size"":""6"",""value"":""25.5cm"",""value_name"":""To...",Not Available,Ary███ fo███ear█████████vt ███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes

In [19]:
subset_df = df[['product_id', 'title', 'category', 'initial_price', 'rating']]

subset_df.head()

   product_id           title   category  initial_price  rating
0     8376765     Lino Perros  backpacks           3995     3.8
1     9136281  Tommy Hilfiger  backpacks           2899     4.5
2    17633752           Lavie  backpacks           2999     4.4
3     1376949          F Gear  backpacks           1675     4.4
4    13939916       MYTRIDENT  bath-robe           2899     4.7

---
## Remove Duplicates

In [20]:
df.duplicated(subset=['product_id']).sum()

np.int64(0)

In [21]:
df = df.drop_duplicates(subset=['product_id'])

df.shape

(1000, 24)

In [6]:
## Creating New Columns

--- VERIFYING DERIVED COLUMN OUTPUT ---
            title   price  quantity  total_amount
0     Lino Perros  3995.0         3       11985.0
1  Tommy Hilfiger  2899.0         4       11596.0
2           Lavie  2999.0         1        2999.0
3          F Gear  1675.0         3        5025.0
4       MYTRIDENT  2899.0         3        8697.0

 ## Creating New Columns

In [22]:
df['price'] = df['initial_price'].astype(float)

In [23]:
np.random.seed(42)

df['quantity'] = np.random.randint(1, 5, size=len(df))

In [24]:
df['total_amount'] = df['price'] * df['quantity']

In [25]:
df[['title', 'price', 'quantity', 'total_amount']].head()

            title   price  quantity  total_amount
0     Lino Perros  3995.0         3       11985.0
1  Tommy Hilfiger  2899.0         4       11596.0
2           Lavie  2999.0         1        2999.0
3          F Gear  1675.0         3        5025.0
4       MYTRIDENT  2899.0         3        8697.0

## Final Dataset

In [27]:
essential_columns = [
    'product_id',
    'title',
    'category',
    'rating',
    'price',
    'quantity',
    'total_amount'
]
df_lean = df[essential_columns]

df_lean.head()

,product_id,title,category,rating,price,quantity,total_amount
0,8376765,Lino Perros,backpacks,3.8,3995.0,3,11985.0
1,9136281,Tommy Hilfiger,backpacks,4.5,2899.0,4,11596.0
2,17633752,Lavie,backpacks,4.4,2999.0,1,2999.0
3,1376949,F Gear,backpacks,4.4,1675.0,3,5025.0
4,13939916,MYTRIDENT,bath-robe,4.7,2899.0,3,8697.0

In [29]:
df_lean.to_csv("final_dataset.csv", index=False)